# Customized workflow for building and deploying a VitePress site to GitHub Pages

name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NPM_CONFIG_NODE_VERSION }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Check Bun version
        run: bun --version

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: bun install

      - name: Build VitePress site
        run: bun run docs:build

      - name: List build directory contents
        run: ls -la docs/.vitepress/dist

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

env:
  NPM_CONFIG_NODE_VERSION: ${{ secrets.NPM_CONFIG_NODE_VERSION }}
  APP_ID: ${{ secrets.APP_ID }}
  API_KEY: ${{ secrets.API_KEY }}
  INDEX_NAME: ${{ secrets.INDEX_NAME }}
  ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
  ASSISTANT_INDEX_NAME: ${{ secrets.ASSISTANT_INDEX_NAME }}