name: Combine Markdown Files for AirRepsGPT

on:
  push:
    branches:
      - main
    paths:
      - docs/**/*.md

jobs:
  combine-markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Combine Markdown Files
        run: |
          # Clear output file
          > ultimateguide.md
          
          # Function to add files from a directory
          add_files_from_dir() {
            local dir="$1"
            local description="$2"
            
            if [ -d "$dir" ]; then
              echo "Adding $description files..."
              find "$dir" -name "*.md" -type f | sort | while read -r file; do
                echo "  - Adding: $file"
                cat "$file" >> ultimateguide.md
              done
            else
              echo "Directory $dir not found, skipping..."
            fi
          }
          
          # Add files in logical order
          add_files_from_dir "docs/introduction" "Introduction"
          add_files_from_dir "docs/dictionary" "Dictionary"
          add_files_from_dir "docs/version-info" "Version Info"
          add_files_from_dir "docs/ordering" "Ordering"
          add_files_from_dir "docs/links" "Links"
          add_files_from_dir "docs/troubleshooting" "Troubleshooting"
          
          # Add remaining top-level files
          find docs -maxdepth 1 -name "*.md" -not -name "index.md" -type f | sort | while read -r file; do
            echo "  - Adding: $file"
            cat "$file" >> ultimateguide.md
          done
          
          echo "✅ Successfully combined all markdown files into ultimateguide.md"
          echo "📊 Total size: $(wc -l < ultimateguide.md) lines"

      - name: Change markdown arrays to jsonl
        run : |
          cat ultimateguide.md | tr -s ' ' | sed 's/ \?| \?/;/g' | sed 's/;-\+.*-\+;//' | sed 's/^;/\["/' | sed 's/;/","/g' | sed 's/,"$/\]/g' > tmp_ultimateguide.md
          # Remove empty lines between JSON arrays
          sed '/^\[/N;s/\]\n\n\[/\]\n\[/g' tmp_ultimateguide.md > ultimateguide.md
          rm tmp_ultimateguide.md

      - name: Upload Combined File as Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 90
          path: ultimateguide.md

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn add openai

      - name: Upload Combined File to OpenAI Assistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          VECTOR_STORE_ID: ${{ secrets.VECTOR_STORE_ID }}
        run: node .github/scripts/upload-to-openai.js
